### PR TITLE
Set root password to alpine

### PR DESCRIPTION
**Pull request by AppInstalleriOSGH**

### CODE REVIEW

**Comment by elihwyma** [comment]
This pull request does not address the root cause of the problem, being `chsh` not functioning correctly due to an incorrect build flag. `prep_bootstrap.sh` fails to set the root password because of this.

**Comment by AppInstalleriOSGH** [comment]
It works for me, but ok. Can you dm me on Twitter please https://twitter.com/AppInstalleriOS

**Comment by elihwyma** [comment]
image

**Comment by AppInstalleriOSGH** [comment]
Ok

**Pull request closed without merging**
